apiVersion: v1
kind: Service

metadata:
  name: notification-db-headless
  namespace: hospital

spec:
  clusterIP: None

  selector:
    app: notification-db

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---

apiVersion: v1
kind: Service

metadata:
  name: notification-db
  namespace: hospital

spec:
  type: ClusterIP

  selector:
    app: notification-db

  ports:
    - name: postgres
      port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: notification-db
  namespace: hospital

spec:
  serviceName: notification-db-headless
  replicas: 1

  selector:
    matchLabels:
      app: notification-db

  template:
    metadata:
      labels:
        app: notification-db

    spec:
      containers:
        - name: postgres

          image: postgres:17

          ports:
            - containerPort: 5432
              name: postgres

          env:
            - name: POSTGRES_DB
              value: notificationdb

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: NOTIFICATION_DB_USERNAME

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: hospital-secrets
                  key: NOTIFICATION_DB_PASSWORD

            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

          volumeMounts:
            - name: notification-db-data
              mountPath: /var/lib/postgresql/data

          readinessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 5

          livenessProbe:
            exec:
              command:
                - sh
                - -c
                - pg_isready -U "$POSTGRES_USER" -d "$POSTGRES_DB"

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5

          resources:
            requests:
              cpu: "100m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

  volumeClaimTemplates:
    - metadata:
        name: notification-db-data

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 2Gi