apiVersion: v1
kind: Secret
metadata:
  name: hospital-secrets
  namespace: hospital

type: Opaque

stringData:
  HOSPITAL_DB_USERNAME: hospital
  HOSPITAL_DB_PASSWORD: hospital123

  NOTIFICATION_DB_USERNAME: notification
  NOTIFICATION_DB_PASSWORD: notification123

  RABBITMQ_USER: hospital
  RABBITMQ_PASSWORD: hospital123