spring.application.name=hospital-notification-service
server.port=8082


eureka.instance.prefer-ip-address=true
#eureka.instance.ip-address=127.0.0.1
eureka.instance.instance-id=${spring.application.name}:${server.port}
eureka.client.service-url.defaultZone=${EUREKA_URL:http://localhost:8888/eureka/}

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}


spring.jpa.hibernate.ddl-auto=update
spring.rabbitmq.host=${RABBITMQ_HOST:localhost}
spring.rabbitmq.port=${RABBITMQ_PORT:5672}
spring.rabbitmq.username=${RABBITMQ_USER:guest}
spring.rabbitmq.password=${RABBITMQ_PASSWORD:guest}


# ACTUATOR / PROMETHEUS
management.endpoints.web.exposure.include=health,info,prometheus
management.endpoint.health.probes.enabled=true

# TRACING
management.tracing.sampling.probability=1.0

# OPENTELEMETRY / TEMPO
management.opentelemetry.tracing.export.otlp.endpoint=${OTEL_ENDPOINT:http://localhost:4318/v1/traces}

# RABBITMQ OBSERVABILITY - CONSUMER
spring.rabbitmq.listener.simple.observation-enabled=true
