spring.application.name=hospital-notification-service

server.port=8082
eureka.client.service-url.defaultZone=http://localhost:8888/eureka/

spring.datasource.url=jdbc:postgresql://localhost:5432/hospital_notification_db
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

spring.jpa.hibernate.ddl-auto=update
